spring:
  application:
    name: code-assessment
  datasource:
    url: jdbc:h2:mem:giftandgo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-giftandgo
  flyway:
    enabled: true
    locations: classpath:/db/migration

giftandgo:
    feature:
      validation: true
    blacklist:
      countries:
        - CN
        - US
        - ES
      isps:
        - "Amazon.com, Inc."
        - "Google LLC"
        - "Microsoft Corporation"
ipapi:
  url: http://ip-api.com/json/
  fields: query,countryCode,isp